/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2020-05-14 11:05:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.uao;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/uao/Footer.jsp", Long.valueOf(1583491420987L));
    _jspx_dependants.put("/uao/Header.jsp", Long.valueOf(1589029980257L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-4.4.1-dist/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-4.4.1-dist/css/bootstrap-grid.css\">\r\n");
      out.write("  \t<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-4.4.1-dist/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-4.4.1-dist/css/Style.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap-4.4.1-dist/js/bootstrap.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap-4.4.1-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap-4.4.1-dist/js/bootstrap.bundle.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap-4.4.1-dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap-4.4.1-dist/js/croppie.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.4/croppie.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.4/croppie.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<title>TutorCabin - Get Best Home Tutors in Indore</title>\r\n");
      out.write(" <script type=\"text/javascript\">  \r\n");
      out.write("        /* Function to Generat Captcha */  \r\n");
      out.write("        function GenerateCaptcha() {  \r\n");
      out.write("            var chr1 = Math.ceil(Math.random() * 10) + '';  \r\n");
      out.write("            var chr2 = Math.ceil(Math.random() * 10) + '';  \r\n");
      out.write("            var chr3 = Math.ceil(Math.random() * 10) + '';  \r\n");
      out.write("  \r\n");
      out.write("            var str = new Array(4).join().replace(/(.|$)/g, function () { return ((Math.random() * 36) | 0).toString(36)[Math.random() < .5 ? \"toString\" : \"toUpperCase\"](); });  \r\n");
      out.write("            var captchaCode = str + chr1 + ' ' + chr2 + ' ' + chr3;  \r\n");
      out.write("            document.getElementById(\"txtCaptcha\").innerHTML= captchaCode ;\r\n");
      out.write("        }  \r\n");
      out.write("        \r\n");
      out.write("        /* Function to Check Password and Re-password */\r\n");
      out.write("        function Validate() {\r\n");
      out.write("            var password = document.getElementById(\"txtPassword\").value;\r\n");
      out.write("            var confirmPassword = document.getElementById(\"txtConfirmPassword\").value;\r\n");
      out.write("            if (password != confirmPassword) {\r\n");
      out.write("                alert(\"Passwords do not match.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("    </script>  \r\n");
      out.write("    \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("/* Dropdown Button */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* The container <div> - needed to position the dropdown content */\r\n");
      out.write(".dropdown {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Dropdown Content (Hidden by Default) */\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  background-color: #f1f1f1;\r\n");
      out.write("  min-width: 160px;\r\n");
      out.write("  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Links inside the dropdown */\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("  color: black;\r\n");
      out.write("  padding: 12px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Change color of dropdown links on hover */\r\n");
      out.write(".dropdown-content a:hover {background-color: #ddd;}\r\n");
      out.write("\r\n");
      out.write("/* Show the dropdown menu on hover */\r\n");
      out.write(".dropdown:hover .dropdown-content {display: block;}\r\n");
      out.write("\r\n");
      out.write("/* Change the background color of the dropdown button when the dropdown content is shown */\r\n");
      out.write("/*.dropdown:hover .dropbtn {background-color: #11bba4d6;}\r\n");
      out.write("*/\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\" GenerateCaptcha()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- header -->\r\n");
      out.write("\t<header style=\"height: 116px; \tbackground-color: #0da8d6;\">\r\n");
      out.write("<img data-placeholder=\"no\" src=\"images/TutorCabin.jpg\" alt=\"TutorCabin\" style=\"padding: 35px 26px 43px 111px;\">\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("  <!-- nav start -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm bg-light navbar-light \">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <ul class=\"navbar-nav navbar-nav mr-auto\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
if(session.getAttribute("tutorEmail")!=null) {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Dashboard.html\">Home&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Blogs.html\">Blogs&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Contact.html\">Contact&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Solved_Materials.html\">Solved Materials</a>\r\n");
      out.write("    </li>\r\n");
      out.write("   </ul> \r\n");
} else if(session.getAttribute("uemail")!=null) {
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Dashboard.html\">Home&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Find_Tutor.html\">Find Tutors&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("     <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Blogs.html\">Blogs&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Contact.html\">Contact&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Solved_Materials.html\">Solved Materials</a>\r\n");
      out.write("    </li>\r\n");
      out.write("   \r\n");
      out.write("  </ul>\r\n");
}
else{

      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Dashboard.html\">Home&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"About.html\" >About&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Join_As_A_Tutor.html\">Join As a Tutor&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Contact.html\">Contact&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Blogs.html\">Blogs&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    </ul>\r\n");
} 
      out.write('\r');
      out.write('\n');

if(session.getAttribute("uemail")!=null)
{

      out.write("\r\n");
      out.write("<span class=\"navbar-text\" style=\"padding-left: 150px; color: #a85486;\">\r\n");
      out.write("    \r\n");
      out.write("   <h5><a style=\"text-decoration: none;\" href=\"logout.html\"> |&nbsp  Logout &nbsp |</a></h5>\r\n");
      out.write("  </span>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</nav>\r\n");

}
else if(session.getAttribute("tutorEmail")!=null) {
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"dropdown\" style=\"margin-right: 10px;margin-top: -15px;\">\r\n");
      out.write("<img src=\"images/");
      out.print( session.getAttribute("tphoto") );
      out.write("\" alt=\"ram\" class=\"dropbtn\" style=\"border-radius:50px;margin-top:14px;\"width=\"30\" height=\"25\">\r\n");
      out.write("  <div class=\"dropdown-content\">\r\n");
      out.write("    <a href=\"teacherProfile.html\">View Profile</a>\r\n");
      out.write("    <a href=\"ChangePic.html\">Change Profile</a>\r\n");
      out.write("    <a href=\"logout.html\">Logout</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<p style=\"margin-bottom: 5px;\"> ");
      out.print( session.getAttribute("tutorName") );
      out.write(" </p>\r\n");
      out.write("</nav>\r\n");
      out.write("\t\r\n");

}
else
{

      out.write("\r\n");
      out.write("<span class=\"navbar-text\" style=\"padding-left:150px; color: #a85486; float:right; \">\r\n");
      out.write("   <h5><a style=\"text-decoration: none;\" href=\"Login.html\"> |&nbsp  Login &nbsp |</a></h5>\r\n");
      out.write("  </span>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");

} 

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- nav End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Middle content start-->\r\n");
      out.write("\r\n");
      out.write("<div style=\"height: 440px;\" class=\"middle_container col-sm-12\">\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin-top: 81px; margin-left: 94px;\" class=\"col-sm-6 float-left\">      \r\n");
      out.write("      \r\n");
      out.write("<div class=\"post-image\" style=\"width: 265px;height: 201px;overflow: hidden; float: left; margin-right: 20px;margin-bottom: 20px;display: inline;background: #fff;position: relative;\">\r\n");
      out.write("     <a href=\"\"></a><span></span></a> <img src=\"images/ben-knapen-906550_960_720-final216.jpg\" width=\"216\" height=\"168\">    \r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("      <h4><a style=\"color: black\" href=\"http://www.tutorcabin.com/uncategorized/2-years-pedagogy-research/\" rel=\"bookmark\" title=\"Permanent Link to 2+ Years of Pedagogy Research\">2+ Years of Pedagogy Research</a></h4>\r\n");
      out.write("        <ul style=\"list-style-type: none; \"><span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span>\r\n");
      out.write("            <li style=\"float: left;\"><a style=\"color: #a4a4a4\" href=\"http://www.tutorcabin.com/author/admin/\" title=\"Posts by admin\" rel=\"author\">admin</a></li>\r\n");
      out.write("            <li style=\"float: left;\">Sep-28-2017</li>\r\n");
      out.write("            <li style=\"float: left;\"><a  style=\"color: #a4a4a4\" href=\"http://www.tutorcabin.com/category/uncategorized/\" rel=\"category tag\">Uncategorized</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <br>\r\n");
      out.write("        We have spent a lot of time in understanding how children think. We regularly train our tutors to impart education in the most suitable manner.\r\n");
      out.write("        <a href=\"http://www.tutorcabin.com/uncategorized/2-years-pedagogy-research/\">Read More</a>\r\n");
      out.write("\r\n");
      out.write("    </div>              \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin-top: 81px; margin-left: 94px;\" class=\"col-sm-4 float-right\">\r\n");
      out.write("   \r\n");
      out.write(" <h4>Find Tutor By Subject</h4>\r\n");
      out.write("<div style=\"background: linear-gradient( to right, #F1531C 0%, #F1531C 24%, #EDEBF0 24%, #EDEBF0 100% ); height: 1px;margin-bottom: 20px;\"></div>\r\n");
      out.write("<select name=\"subject\" id=\"lct-widget-subject\" class=\"postform\">\r\n");
      out.write("    <option class=\"level-0\" value=\"test-preparation\">Test Preparation</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"iit-jee\">&nbsp;&nbsp;&nbsp;IIT JEE</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"gre\">&nbsp;&nbsp;&nbsp;GRE</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"gmat\">&nbsp;&nbsp;&nbsp;GMAT</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"cet\">&nbsp;&nbsp;&nbsp;CET</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bitsat\">&nbsp;&nbsp;&nbsp;BITSAT</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"aipmt\">&nbsp;&nbsp;&nbsp;AIPMT</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"aieee\">&nbsp;&nbsp;&nbsp;AIEEE</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"pre-school\">Pre-school</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mathematics-pre-school\">&nbsp;&nbsp;&nbsp;Mathematics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"hindi-pre-school\">&nbsp;&nbsp;&nbsp;Hindi</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"evs-pre-school\">&nbsp;&nbsp;&nbsp;EVS</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"english-pre-school\">&nbsp;&nbsp;&nbsp;English</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"mba-bba\">MBA and BBA</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"management-subjects\">&nbsp;&nbsp;&nbsp;Management Subjects</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"cat-mba-entrance\">&nbsp;&nbsp;&nbsp;CAT (MBA Entrance)</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bba-subjects\">&nbsp;&nbsp;&nbsp;BBA Subjects</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bba-entrance\">&nbsp;&nbsp;&nbsp;BBA Entrance</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"maths\">maths</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"primary\">&nbsp;&nbsp;&nbsp;primary</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"foreign-languages\">Foreign Languages</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"spoken-english\">&nbsp;&nbsp;&nbsp;Spoken English</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"spanish\">&nbsp;&nbsp;&nbsp;Spanish</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"french\">&nbsp;&nbsp;&nbsp;French</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"english-foreign-languages\">&nbsp;&nbsp;&nbsp;English</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"canadian-accent\">&nbsp;&nbsp;&nbsp;Canadian accent</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"british-english\">&nbsp;&nbsp;&nbsp;British English</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"american-english\">&nbsp;&nbsp;&nbsp;American English</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"american-accent\">&nbsp;&nbsp;&nbsp;American accent</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"english-language\">English Language</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"spoken-english-english-class-4\">&nbsp;&nbsp;&nbsp;Spoken English</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"presentation-skills-preparation\">&nbsp;&nbsp;&nbsp;Presentation Skills Preparation</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"personality-development\">&nbsp;&nbsp;&nbsp;Personality Development</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"interview-skills-preparation\">&nbsp;&nbsp;&nbsp;Interview Skills Preparation</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"group-discussion\">&nbsp;&nbsp;&nbsp;Group Discussion</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"grammar\">&nbsp;&nbsp;&nbsp;Grammar</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"competitive-exam-level\">&nbsp;&nbsp;&nbsp;competitive Exam Level</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"engineering-subjects\">Engineering Subjects</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"thermodynamics\">&nbsp;&nbsp;&nbsp;Thermodynamics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"production-engineering-subjects\">&nbsp;&nbsp;&nbsp;Production</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mechanical-engineering-subjects\">&nbsp;&nbsp;&nbsp;Mechanical</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mathematics-engineering-subjects\">&nbsp;&nbsp;&nbsp;Mathematics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"it\">&nbsp;&nbsp;&nbsp;IT</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"instrumentation\">&nbsp;&nbsp;&nbsp;Instrumentation</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"electronics\">&nbsp;&nbsp;&nbsp;Electronics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"electrical\">&nbsp;&nbsp;&nbsp;Electrical</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"drawing\">&nbsp;&nbsp;&nbsp;Drawing</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"computer-engineering-subjects\">&nbsp;&nbsp;&nbsp;Computer</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"civil\">&nbsp;&nbsp;&nbsp;Civil</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"chemical\">&nbsp;&nbsp;&nbsp;Chemical</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bio-technology\">&nbsp;&nbsp;&nbsp;Bio Technology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"autocad-training\">&nbsp;&nbsp;&nbsp;AutoCAD Training</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"aeronautical\">&nbsp;&nbsp;&nbsp;Aeronautical</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"college-level\">College Level</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"zoology\">&nbsp;&nbsp;&nbsp;Zoology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sociology\">&nbsp;&nbsp;&nbsp;Sociology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"psychology\">&nbsp;&nbsp;&nbsp;Psychology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"political-science\">&nbsp;&nbsp;&nbsp;Political Science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"physiology\">&nbsp;&nbsp;&nbsp;Physiology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"philosophy\">&nbsp;&nbsp;&nbsp;Philosophy</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"microbiology\">&nbsp;&nbsp;&nbsp;MicroBiology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mass-communication\">&nbsp;&nbsp;&nbsp;Mass communication</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"indirect-tax\">&nbsp;&nbsp;&nbsp;Indirect Tax</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"hotel-management\">&nbsp;&nbsp;&nbsp;Hotel Management</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"history\">&nbsp;&nbsp;&nbsp;History</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"geography\">&nbsp;&nbsp;&nbsp;Geography</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"food-nutrition\">&nbsp;&nbsp;&nbsp;Food &amp; Nutrition</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"financial-management\">&nbsp;&nbsp;&nbsp;Financial Management</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"economics\">&nbsp;&nbsp;&nbsp;Economics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"computer-science-college-level\">&nbsp;&nbsp;&nbsp;Computer Science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"chemistry-college-level\">&nbsp;&nbsp;&nbsp;Chemistry</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"business-maths-college-level\">&nbsp;&nbsp;&nbsp;Business Maths</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"botany\">&nbsp;&nbsp;&nbsp;Botany</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bio-informatics\">&nbsp;&nbsp;&nbsp;Bio-informatics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bio-chemistry\">&nbsp;&nbsp;&nbsp;Bio Chemistry</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"anthropology\">&nbsp;&nbsp;&nbsp;Anthropology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"accountancy\">&nbsp;&nbsp;&nbsp;Accountancy</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"class-9-10\">Class 9-10</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"social-science-class-9-10\">&nbsp;&nbsp;&nbsp;Social science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"science-class-9-10\">&nbsp;&nbsp;&nbsp;Science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sanskrit-class-9-10\">&nbsp;&nbsp;&nbsp;Sanskrit</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"painting\">&nbsp;&nbsp;&nbsp;Painting</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"music\">&nbsp;&nbsp;&nbsp;Music</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mathematics-class-9-10\">&nbsp;&nbsp;&nbsp;Mathematics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"it-class-9-10\">&nbsp;&nbsp;&nbsp;IT (Information Technology)</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"home-science\">&nbsp;&nbsp;&nbsp;Home science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"hindi-class-9-10\">&nbsp;&nbsp;&nbsp;Hindi</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"french-class-9-10\">&nbsp;&nbsp;&nbsp;French</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"english-class-9-10\">&nbsp;&nbsp;&nbsp;English</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"all-subjects-class-9-10\">&nbsp;&nbsp;&nbsp;All subjects</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"class-6-8\">Class 6-8</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"social-science-class-6th-8th\">&nbsp;&nbsp;&nbsp;Social science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"science\">&nbsp;&nbsp;&nbsp;Science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mathematics\">&nbsp;&nbsp;&nbsp;Mathematics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"hindi-class-6th-8th\">&nbsp;&nbsp;&nbsp;Hindi</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"english-class-6th-8th\">&nbsp;&nbsp;&nbsp;English</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"computer-class-6th-8th\">&nbsp;&nbsp;&nbsp;Computer</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"all-subjects-class-6th-8th\">&nbsp;&nbsp;&nbsp;All subjects</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"class-12\">Class 12</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sociology-class-12\">&nbsp;&nbsp;&nbsp;Sociology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sanskrit-class-12\">&nbsp;&nbsp;&nbsp;Sanskrit</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"psychology-class-12\">&nbsp;&nbsp;&nbsp;Psychology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"political-science-class-12\">&nbsp;&nbsp;&nbsp;Political Science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"physics-class-12\">&nbsp;&nbsp;&nbsp;Physics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"physical-education-class-12\">&nbsp;&nbsp;&nbsp;Physical Education</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"philosophy-class-12\">&nbsp;&nbsp;&nbsp;Philosophy</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"multimedia-and-webtech-class-12\">&nbsp;&nbsp;&nbsp;Multimedia and Webtech</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mathematics-class-12\">&nbsp;&nbsp;&nbsp;Mathematics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"legal-studies-class-12\">&nbsp;&nbsp;&nbsp;Legal Studies</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"informatics-practices-class-12\">&nbsp;&nbsp;&nbsp;Informatics Practices</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"home-science-class-12\">&nbsp;&nbsp;&nbsp;Home Science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"history-class-12\">&nbsp;&nbsp;&nbsp;History</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"hindi-class-12\">&nbsp;&nbsp;&nbsp;Hindi</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"geography-class-12\">&nbsp;&nbsp;&nbsp;Geography</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"financial-market-management-class-12\">&nbsp;&nbsp;&nbsp;Financial Market Management</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"entrepreneurship-class-12\">&nbsp;&nbsp;&nbsp;Entrepreneurship</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"english-class-12\">&nbsp;&nbsp;&nbsp;English</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"engineering-graphics-class-12\">&nbsp;&nbsp;&nbsp;Engineering Graphics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"economics-class-12\">&nbsp;&nbsp;&nbsp;Economics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"computer-science-class-12\">&nbsp;&nbsp;&nbsp;Computer Science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"chemistry-class-12\">&nbsp;&nbsp;&nbsp;Chemistry</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"business-studies-class-12\">&nbsp;&nbsp;&nbsp;Business Studies</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"biotechnology-class-12\">&nbsp;&nbsp;&nbsp;Biotechnology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"biology-class-12\">&nbsp;&nbsp;&nbsp;Biology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"accountancy-class-12\">&nbsp;&nbsp;&nbsp;Accountancy</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"class-11\">Class 11</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sociology-class-11\">&nbsp;&nbsp;&nbsp;Sociology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sanskrit-class-11\">&nbsp;&nbsp;&nbsp;Sanskrit</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"psychology-class-11\">&nbsp;&nbsp;&nbsp;Psychology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"political-science-class-11\">&nbsp;&nbsp;&nbsp;Political Science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"physics\">&nbsp;&nbsp;&nbsp;Physics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"physical-education\">&nbsp;&nbsp;&nbsp;Physical Education</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"philosophy-class-11\">&nbsp;&nbsp;&nbsp;Philosophy</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"multimedia-and-webtech\">&nbsp;&nbsp;&nbsp;Multimedia and Webtech</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mathematics-class-11\">&nbsp;&nbsp;&nbsp;Mathematics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"legal-studies\">&nbsp;&nbsp;&nbsp;Legal Studies</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"informatics-practices\">&nbsp;&nbsp;&nbsp;Informatics Practices</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"home-science-class-11\">&nbsp;&nbsp;&nbsp;Home Science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"history-class-11\">&nbsp;&nbsp;&nbsp;History</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"hindi-class-11\">&nbsp;&nbsp;&nbsp;Hindi</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"geography-class-11\">&nbsp;&nbsp;&nbsp;Geography</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"financial-market-management\">&nbsp;&nbsp;&nbsp;Financial Market Management</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"entrepreneurship\">&nbsp;&nbsp;&nbsp;Entrepreneurship</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"english-class-11\">&nbsp;&nbsp;&nbsp;English</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"engineering-graphics\">&nbsp;&nbsp;&nbsp;Engineering Graphics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"economics-class-11\">&nbsp;&nbsp;&nbsp;Economics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"computer-science\">&nbsp;&nbsp;&nbsp;Computer Science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"chemistry-class-11\">&nbsp;&nbsp;&nbsp;Chemistry</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"business-studies\">&nbsp;&nbsp;&nbsp;Business Studies</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"biotechnology\">&nbsp;&nbsp;&nbsp;Biotechnology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"biology-class-11\">&nbsp;&nbsp;&nbsp;Biology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"accountancy-class-11\">&nbsp;&nbsp;&nbsp;Accountancy</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"class-1-5\">Class 1-5</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"social-science\">&nbsp;&nbsp;&nbsp;Social science</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sanskrit\">&nbsp;&nbsp;&nbsp;Sanskrit</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mathematics-class-1-5\">&nbsp;&nbsp;&nbsp;Mathematics</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"hindi\">&nbsp;&nbsp;&nbsp;Hindi</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"french-class-5\">&nbsp;&nbsp;&nbsp;French</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"evs\">&nbsp;&nbsp;&nbsp;EVS</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"english\">&nbsp;&nbsp;&nbsp;English</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"computer\">&nbsp;&nbsp;&nbsp;Computer</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"all-subjects\">&nbsp;&nbsp;&nbsp;All Subjects</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"chemistry-biology\">chemistry, biology</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"chemistry\">&nbsp;&nbsp;&nbsp;Chemistry</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"biology\">&nbsp;&nbsp;&nbsp;Biology</option>\r\n");
      out.write("</select>\r\n");
      out.write("<input type=\"submit\" value=\"go Â»\"></form>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<h4 style=\"margin-top: 48px;\">Find Tutor By City</h4>\r\n");
      out.write("\r\n");
      out.write("<div style=\"background: linear-gradient( to right, #F1531C 0%, #F1531C 24%, #EDEBF0 24%, #EDEBF0 100% ); height: 1px;margin-bottom: 20px;\"></div>\r\n");
      out.write("<select name=\"area\" id=\"lct-widget-area\" class=\"postform\">\r\n");
      out.write("    <option class=\"level-0\" value=\"mumbai\">Mumbai&nbsp;</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"indore\">Indore&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"yeshwant-road\">&nbsp;&nbsp;&nbsp;Yeshwant Road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"yashwant-nagar\">&nbsp;&nbsp;&nbsp;Yashwant Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"vishnu-puri\">&nbsp;&nbsp;&nbsp;Vishnu Puri&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"vijay-nagar\">&nbsp;&nbsp;&nbsp;Vijay Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"vandana-nagar\">&nbsp;&nbsp;&nbsp;Vandana Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"vallabh-nagar\">&nbsp;&nbsp;&nbsp;Vallabh Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"vaishali-nagar\">&nbsp;&nbsp;&nbsp;Vaishali Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"vaibhav-nagar\">&nbsp;&nbsp;&nbsp;Vaibhav Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"tulsi-nagar-indore\">&nbsp;&nbsp;&nbsp;Tulsi Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"tukoganj\">&nbsp;&nbsp;&nbsp;Tukoganj&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"triveni-colony\">&nbsp;&nbsp;&nbsp;Triveni Colony&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"tillor-khurd\">&nbsp;&nbsp;&nbsp;Tillor Khurd&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"tilak-nagar\">&nbsp;&nbsp;&nbsp;Tilak Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"tehsil\">&nbsp;&nbsp;&nbsp;Tehsil&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sukhliya\">&nbsp;&nbsp;&nbsp;Sukhliya&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sudama-nagar\">&nbsp;&nbsp;&nbsp;Sudama Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"subhash-nagar\">&nbsp;&nbsp;&nbsp;Subhash Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"srinagar\">&nbsp;&nbsp;&nbsp;Srinagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"south-tukoganj\">&nbsp;&nbsp;&nbsp;South Tukoganj&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"siyaganj\">&nbsp;&nbsp;&nbsp;Siyaganj&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sector-23-d\">&nbsp;&nbsp;&nbsp;Sector 23-D&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"scheme-number-54\">&nbsp;&nbsp;&nbsp;Scheme Number-54&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sanwer-road\">&nbsp;&nbsp;&nbsp;Sanwer Road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sangam-nagar\">&nbsp;&nbsp;&nbsp;Sangam Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"saket-nagar\">&nbsp;&nbsp;&nbsp;Saket Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sahara-city-homes\">&nbsp;&nbsp;&nbsp;Sahara City Homes&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"sadar-bazar\">&nbsp;&nbsp;&nbsp;Sadar Bazar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"rss-nagar\">&nbsp;&nbsp;&nbsp;RSS Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"rnt-marg\">&nbsp;&nbsp;&nbsp;RNT Marg&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"ring-road\">&nbsp;&nbsp;&nbsp;Ring Road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"regal\">&nbsp;&nbsp;&nbsp;Regal&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"ravishankar-shukla-nagar\">&nbsp;&nbsp;&nbsp;Ravishankar Shukla Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"rau\">&nbsp;&nbsp;&nbsp;Rau&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"ratlam-kothi\">&nbsp;&nbsp;&nbsp;Ratlam Kothi&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"rasoma-circle\">&nbsp;&nbsp;&nbsp;Rasoma Circle&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"ranipura\">&nbsp;&nbsp;&nbsp;Ranipura&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"rambagh\">&nbsp;&nbsp;&nbsp;Rambagh&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"rajwada\">&nbsp;&nbsp;&nbsp;Rajwada&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"rajiv-gandhi-square\">&nbsp;&nbsp;&nbsp;Rajiv Gandhi Square&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"rajendra-nagar\">&nbsp;&nbsp;&nbsp;Rajendra Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"raj-mohalla\">&nbsp;&nbsp;&nbsp;Raj Mohalla&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"radio-colony\">&nbsp;&nbsp;&nbsp;Radio Colony&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"race-course-road-indore\">&nbsp;&nbsp;&nbsp;Race Course Road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"pipliyahana\">&nbsp;&nbsp;&nbsp;Pipliyahana&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"patnipura\">&nbsp;&nbsp;&nbsp;Patnipura&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"patni-pura\">&nbsp;&nbsp;&nbsp;Patni Pura&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"palsikar-colony\">&nbsp;&nbsp;&nbsp;Palsikar Colony&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"palda\">&nbsp;&nbsp;&nbsp;Palda&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"palasia\">&nbsp;&nbsp;&nbsp;Palasia&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"omex-city\">&nbsp;&nbsp;&nbsp;Omex City&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"nipania\">&nbsp;&nbsp;&nbsp;Nipania&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"new-rani-bagh\">&nbsp;&nbsp;&nbsp;New Rani Bagh&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"navlakha\">&nbsp;&nbsp;&nbsp;Navlakha&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"nandanvan-colony\">&nbsp;&nbsp;&nbsp;Nandanvan Colony&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"nanda-nagar\">&nbsp;&nbsp;&nbsp;Nanda Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"nanakheda\">&nbsp;&nbsp;&nbsp;Nanakheda&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"musakhedi\">&nbsp;&nbsp;&nbsp;Musakhedi&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"murai-mohalla\">&nbsp;&nbsp;&nbsp;Murai Mohalla&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mr-10-road\">&nbsp;&nbsp;&nbsp;MR-10 road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mhow-naka\">&nbsp;&nbsp;&nbsp;Mhow Naka&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mhow\">&nbsp;&nbsp;&nbsp;Mhow&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mari-mata-square\">&nbsp;&nbsp;&nbsp;Mari Mata Square&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"manoramaganj\">&nbsp;&nbsp;&nbsp;Manoramaganj&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"manglia\">&nbsp;&nbsp;&nbsp;Manglia&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"manbhavan-nagar\">&nbsp;&nbsp;&nbsp;Manbhavan Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"malwa-mill\">&nbsp;&nbsp;&nbsp;Malwa Mill&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"malharganj\">&nbsp;&nbsp;&nbsp;Malharganj&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"maharani-road\">&nbsp;&nbsp;&nbsp;Maharani Road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"mahalaxmi-nagar\">&nbsp;&nbsp;&nbsp;Mahalaxmi Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"madhumilan\">&nbsp;&nbsp;&nbsp;Madhumilan&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"lokmanya-nagar\">&nbsp;&nbsp;&nbsp;Lokmanya Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"limbodi\">&nbsp;&nbsp;&nbsp;Limbodi&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"l-i-g-colony\">&nbsp;&nbsp;&nbsp;L.I.G. Colony&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"kumar-khadi\">&nbsp;&nbsp;&nbsp;Kumar Khadi&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"krishi-mandi\">&nbsp;&nbsp;&nbsp;Krishi Mandi&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"khatiwala-road\">&nbsp;&nbsp;&nbsp;Khatiwala Tank&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"khatipura\">&nbsp;&nbsp;&nbsp;Khatipura&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"khandwa-road\">&nbsp;&nbsp;&nbsp;Khandwa Road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"khajuri-bazar\">&nbsp;&nbsp;&nbsp;Khajuri Bazar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"khajrana\">&nbsp;&nbsp;&nbsp;Khajrana&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"kelod-kartal\">&nbsp;&nbsp;&nbsp;Kelod Kartal&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"kanchan-bagh\">&nbsp;&nbsp;&nbsp;Kanchan Bagh&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"kanadiya\">&nbsp;&nbsp;&nbsp;kanadiya&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"kalyani-nagar-indore\">&nbsp;&nbsp;&nbsp;Kalyani Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"javeri-bagh\">&nbsp;&nbsp;&nbsp;Javeri Bagh&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"jaora-compound\">&nbsp;&nbsp;&nbsp;Jaora Compound&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"jail-road\">&nbsp;&nbsp;&nbsp;Jail Road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"indore-army\">&nbsp;&nbsp;&nbsp;Indore Army&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"imli-bazar\">&nbsp;&nbsp;&nbsp;Imli Bazar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"high-court\">&nbsp;&nbsp;&nbsp;High Court&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"gwal-toli\">&nbsp;&nbsp;&nbsp;Gwal Toli&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"gurunanak-chowk\">&nbsp;&nbsp;&nbsp;Gurunanak Chowk&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"gulab-bagh\">&nbsp;&nbsp;&nbsp;Gulab Bagh&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"geeta-nagar\">&nbsp;&nbsp;&nbsp;Geeta Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"geeta-bhawan\">&nbsp;&nbsp;&nbsp;Geeta Bhawan&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"gandhi-nagar\">&nbsp;&nbsp;&nbsp;Gandhi Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"fc-ganj-edso\">&nbsp;&nbsp;&nbsp;FC Ganj EDSO&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"durgi-road\">&nbsp;&nbsp;&nbsp;Durgi Road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"dhar-road\">&nbsp;&nbsp;&nbsp;Dhar road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"deoguradia\">&nbsp;&nbsp;&nbsp;deoguradia&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"ddu-nagar\">&nbsp;&nbsp;&nbsp;DDU Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"dawa-bazar\">&nbsp;&nbsp;&nbsp;Dawa Bazar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"collectorate\">&nbsp;&nbsp;&nbsp;Collectorate&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"cloth-market\">&nbsp;&nbsp;&nbsp;Cloth Market&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"chandra-nagar\">&nbsp;&nbsp;&nbsp;Chandra Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"chandan-nagar\">&nbsp;&nbsp;&nbsp;Chandan Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"cgo-complex\">&nbsp;&nbsp;&nbsp;CGO Complex&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"cantt-indore\">&nbsp;&nbsp;&nbsp;Cantt Indore&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"by-pass\">&nbsp;&nbsp;&nbsp;By Pass&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bijasanroad\">&nbsp;&nbsp;&nbsp;BijasanRoad&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bijalpur\">&nbsp;&nbsp;&nbsp;Bijalpur&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bicholi-mardana\">&nbsp;&nbsp;&nbsp;Bicholi Mardana&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bhawrasla\">&nbsp;&nbsp;&nbsp;Bhawrasla&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bhagirath-pura\">&nbsp;&nbsp;&nbsp;Bhagirath Pura&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"barlai-jagir\">&nbsp;&nbsp;&nbsp;Barlai Jagir&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"banganga\">&nbsp;&nbsp;&nbsp;Banganga&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bangali-square\">&nbsp;&nbsp;&nbsp;Bangali Square&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"baloda-tkun\">&nbsp;&nbsp;&nbsp;Baloda Tkun&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"badwali-chowk\">&nbsp;&nbsp;&nbsp;Badwali Chowk&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"badodia-khan\">&nbsp;&nbsp;&nbsp;Badodia Khan&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"badia-keema\">&nbsp;&nbsp;&nbsp;Badia Keema&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"bada-ganpati\">&nbsp;&nbsp;&nbsp;Bada Ganpati&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"azad-nagar\">&nbsp;&nbsp;&nbsp;Azad Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"army-headquarters\">&nbsp;&nbsp;&nbsp;Army Headquarters&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"anoop-nagar\">&nbsp;&nbsp;&nbsp;Anoop Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"annapurna-road\">&nbsp;&nbsp;&nbsp;Annapurna Road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"anand-bazar\">&nbsp;&nbsp;&nbsp;Anand Bazar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"agrawal-nagar\">&nbsp;&nbsp;&nbsp;Agrawal Nagar&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"aerodrum-road\">&nbsp;&nbsp;&nbsp;Aerodrum road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"a-b-road\">&nbsp;&nbsp;&nbsp;A.B.road&nbsp;</option>\r\n");
      out.write("    <option class=\"level-1\" value=\"56-dukaan\">&nbsp;&nbsp;&nbsp;56 Dukaan&nbsp;</option>\r\n");
      out.write("    <option class=\"level-0\" value=\"bhopal\">Bhopal&nbsp;</option>\r\n");
      out.write("</select>\r\n");
      out.write("<input type=\"submit\" value=\"go Â»\"></form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Middle content End-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  footer start-->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"jumbotron\" style=\"height:450px\">\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("<div id=\"d1\" class=\"col-sm-3  float-left\" >Contact Us<hr>\r\n");
      out.write("           Address:<br>\r\n");
      out.write("           indore pin 452005\r\n");
      out.write("           <br>\r\n");
      out.write("           contact:<br>\r\n");
      out.write("           <iframe src=\"https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d29437.929275521048!2d75.87074083955078!3d22.737860200000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1581743478935!5m2!1sen!2sin\" width=\"200\" height=\"220\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\"></iframe>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"d1\" class=\"col-sm-3  float-left\"  >Find Tutor In Indore<hr>\r\n");
      out.write("           <ul style=\"overflow: scroll;height: 300px\">\r\n");
      out.write("    <li><a href=\"#\">Khatipura</a> (1)</li>\r\n");
      out.write("    <li><a href=\"#\">Krishi Mandi</a> (1)</li>\r\n");
      out.write("    <li><a href=\"#\">Krishi Mandi</a> (1)\r\n");
      out.write("    <li><a href=\"#\">L.I.G. Colony</a> (1)\r\n");
      out.write("\r\n");
      out.write("    <li><a href=\"#\">Limbodi</a> (1)\r\n");
      out.write("\r\n");
      out.write("   <li><a href=\"#\">Lokmanya Nagar</a> (1)\r\n");
      out.write("\r\n");
      out.write("    <li><a href=\"#\">Mahalaxmi Nagar</a> (1)\r\n");
      out.write("\r\n");
      out.write("    <li><a href=\"#\">Malharganj</a> (1)\r\n");
      out.write("\r\n");
      out.write("    <li><a href=\"#\">Manbhavan Nagar</a> (1)\r\n");
      out.write("\r\n");
      out.write("    <li><a href=\"#\">Manglia</a> (1)\r\n");
      out.write("\r\n");
      out.write("    <li><a href=\"#\">Mari Mata Square</a> (1)\r\n");
      out.write("\r\n");
      out.write("    <li><a href=\"#\">Mhow</a> (1)\r\n");
      out.write("\r\n");
      out.write("    <li><a href=\"#\">Mhow Naka</a> (1)\r\n");
      out.write("\r\n");
      out.write("<li><a href=\"#\">Murai Mohalla</a> (1)\r\n");
      out.write("\r\n");
      out.write("    <li><a href=\"#\">Musakhedi</a> (1)\r\n");
      out.write("<li><a href=\"#\">Nanakheda</a> (1)\r\n");
      out.write("<li><a href=\"#\">Nanda Nagar</a> (1)\r\n");
      out.write("<li><a href=\"#\">Nandanvan Colony</a> (1)</li>\r\n");
      out.write("    <li><a href=\"#\">Navlakha</a> (1)</li>\r\n");
      out.write("    <li><a href=\"#\">New Rani Bagh</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("    <li><a href=\"#\">Omex City</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("    <li><a href=\"#\">Palasia</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("    <li><a href=\"#\">Palda</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Palsikar Colony</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Patni Pura</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Patnipura</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Pipliyahana</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Radio Colony</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Raj Mohalla</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Rajendra Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Rajwada</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Ranipura</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Rau</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Sadar Bazar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Sahara City Homes</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Sangam Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Sukhliya</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Tehsil</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Tilak Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Triveni Colony</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Tukoganj</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Vaibhav Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Vaishali Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Vandana Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Vijay Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Vishnu Puri</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Anoop Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Azad Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Bada Ganpati</a> (1)\r\n");
      out.write("</li/>\r\n");
      out.write("<li><a href=\"#\">Badia Keema</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Banganga</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Bhagirath Pura</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Bhawrasla</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Bicholi Mardana</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Bijalpur</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Chandan Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Chandra Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">deoguradia</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">kanadiya</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">MR-10 road</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Aerodrum road</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">A.B.road</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Race Course Road</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Maharani Road</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Saket Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("    <li><a href=\"#\">Annapurna Road</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Khajuri Bazar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Khatiwala Tank</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Dhar road</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">RNT Marg</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Sector 23-D</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Badodia Khan</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Barlai Jagir</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Army Headquarters</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Baloda Tkun</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Agrawal Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Badwali Chowk</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">BijasanRoad</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">CGO Complex</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write(" <li><a href=\"#\">Cloth Market</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">FC Ganj EDSO</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Gandhi Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Jail Road</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Gurunanak Chowk</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write(" <li><a href=\"#\">Collectorate</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">High Court</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Regal</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Imli Bazar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Geeta Bhawan</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Geeta Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("    <li><a href=\"#\">Anand Bazar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Jaora Compound</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Dawa Bazar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">By Pass</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Bangali Square</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Nipania</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Kalyani Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Gulab Bagh</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Rajiv Gandhi Square</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Siyaganj</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Manoramaganj</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">South Tukoganj</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Srinagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Malwa Mill</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Yeshwant Road</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Rambagh</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Ravishankar Shukla Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Madhumilan</a> (1)\r\n");
      out.write("</li><li><a href=\"#\">Vallabh Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">DDU Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Sudama Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write(" <li><a href=\"#\">RSS Nagar</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Kumar Khadi</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Javeri Bagh</a> (1)\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Gwal Toli</a> (1)\r\n");
      out.write("\r\n");
      out.write("<li><a href=\"#\">Sanwer Road</a> (1)\r\n");
      out.write("\r\n");
      out.write("<li><a href=\"#\">Yashwant Nagar</a> (1)\r\n");
      out.write("<li><a href=\"#\">Kelod Kartal</a> (1)\r\n");
      out.write("\r\n");
      out.write("<li><a href=\"#\">Tillor Khurd</a> (1)\r\n");
      out.write("<li><a href=\"#\">Ratlam Kothi</a> (1)\r\n");
      out.write("<li><a href=\"#\">Rasoma Circle</a> (1)\r\n");
      out.write("\r\n");
      out.write("<li><a href=\"#\">Ring Road</a> (1)\r\n");
      out.write("<li><a href=\"#\">Subhash Nagar</a> (1)\r\n");
      out.write("<li><a href=\"#\">Scheme Number-54</a> (1)\r\n");
      out.write("<li><a href=\"#\">Kanchan Bagh</a> (1)\r\n");
      out.write("<li><a href=\"#\">Khandwa Road</a> (1)\r\n");
      out.write("<li><a href=\"#\">Durgi Road</a> (1)\r\n");
      out.write("<li><a href=\"#\">56 Dukaan</a> (1)\r\n");
      out.write("<li><a href=\"#\">Cantt Indore</a> (1)\r\n");
      out.write("<li><a href=\"#\">Tulsi Nagar</a> (1)\r\n");
      out.write("<li><a href=\"#\">Indore Army</a> (1)\r\n");
      out.write("\r\n");
      out.write("           </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"d1\" class=\"col-sm-3  float-left\"  >Find Tutor For Collage Level Subject<hr>\r\n");
      out.write("           <ul style=\"overflow: scroll;height: 280px\">\r\n");
      out.write("        <li><a href=\"#\">Computer Science</a> (52)</li>\r\n");
      out.write("    <li><a href=\"#\">Accountancy</a> (49)</li>\r\n");
      out.write("    <li><a href=\"#\">Economics</a> (46)</li>\r\n");
      out.write("    <li><a href=\"#\">History</a> (43)</li>\r\n");
      out.write("    <li><a href=\"#\">Business Maths</a> (43)</li>\r\n");
      out.write("    <li><a href=\"#\">Geography</a> (40)</li>\r\n");
      out.write("    <li><a href=\"#\">Indirect Tax</a> (39)</li>\r\n");
      out.write("    <li><a href=\"#\">Political Science</a> (38)</li>\r\n");
      out.write("    <li><a href=\"#\">Financial Management</a> (37)</li>\r\n");
      out.write("    <li><a href=\"#\">Zoology</a> (37)</li>\r\n");
      out.write("    <li\"><a href=\"#\">Chemistry</a> (37)</li>\r\n");
      out.write("    <li><a href=\"#\">Hotel Management</a> (36)</li>\r\n");
      out.write("    <li><a href=\"#\">Mass communication</a> (36)</li>\r\n");
      out.write("    <li><a href=\"#\">Philosophy</a> (35)</li>\r\n");
      out.write("    <li><a href=\"#\">Psychology</a> (35)</li>\r\n");
      out.write("    <li><a href=\"#\">Botany</a> (35)</li>\r\n");
      out.write("    <li><a href=\"#\">MicroBiology</a> (34)</li>\r\n");
      out.write("    <li><a href=\"#\">Bio Chemistry</a> (34)</li>\r\n");
      out.write("    <li><a href=\"#\">Physiology</a> (33)</li>\r\n");
      out.write("    <li><a href=\"#\">Sociology</a> (33)</li>\r\n");
      out.write("    <li><a href=\"#\">Bio-informatics</a> (33)</li>\r\n");
      out.write("    <li><a href=\"#\">Anthropology</a> (32)</li>\r\n");
      out.write("    <li><a href=\"#\">Food &amp; Nutrition</a> (31)</li> \r\n");
      out.write("              </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"d1\" class=\"col-sm-3  float-left\"  >Link<hr>\r\n");
      out.write("  <ul style=\"overflow: scroll;height: 300px\"><li id=\"menu-item-376\" class=\"menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-376\"><a href=\"Dashboard.html\">Home</a></li>\r\n");
      out.write("<li id=\"menu-item-377\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-377\"><a href=\"#\">About</a></li>\r\n");
      out.write("<li id=\"menu-item-378\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-378\"><a href=\"#\">Find Tutors</a></li>\r\n");
      out.write("<li id=\"menu-item-379\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-379\"><a href=\"Blogs.html\">Blogs</a></li>\r\n");
      out.write("<li id=\"menu-item-380\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-380\"><a href=\"#\">Contact</a></li>\r\n");
      out.write("<li id=\"menu-item-381\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-381\"><a href=\"#\">Join As a Tutor</a></li>\r\n");
      out.write("<li id=\"menu-item-383\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-383\"><a href=\"Solved_Materials.html\">Solved Materials</a></li>\r\n");
      out.write("<li id=\"menu-item-384\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-384\"><a href=\"#\">Tutor FAQâs</a></li>\r\n");
      out.write("<li id=\"menu-item-382\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-382\"><a href=\"#\">Payment Mode</a></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("       </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
