/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2020-04-11 12:20:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.uao;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.hibernate.Query;
import template.Datahelper;

public final class editInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/uao/Header.jsp", Long.valueOf(1586542633520L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("template.Datahelper");
    _jspx_imports_classes.add("org.hibernate.Query");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("  \t<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-4.4.1-dist/css/bootstrap.min.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap-4.4.1-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-4.4.1-dist/css/Style.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>TutorCabin - Get Best Home Tutors in Indore</title>\r\n");
      out.write(" <script type=\"text/javascript\">  \r\n");
      out.write("        /* Function to Generat Captcha */  \r\n");
      out.write("        function GenerateCaptcha() {  \r\n");
      out.write("            var chr1 = Math.ceil(Math.random() * 10) + '';  \r\n");
      out.write("            var chr2 = Math.ceil(Math.random() * 10) + '';  \r\n");
      out.write("            var chr3 = Math.ceil(Math.random() * 10) + '';  \r\n");
      out.write("  \r\n");
      out.write("            var str = new Array(4).join().replace(/(.|$)/g, function () { return ((Math.random() * 36) | 0).toString(36)[Math.random() < .5 ? \"toString\" : \"toUpperCase\"](); });  \r\n");
      out.write("            var captchaCode = str + chr1 + ' ' + chr2 + ' ' + chr3;  \r\n");
      out.write("            document.getElementById(\"txtCaptcha\").innerHTML= captchaCode ;\r\n");
      out.write("        }  \r\n");
      out.write("        \r\n");
      out.write("        /* Function to Check Password and Re-password */\r\n");
      out.write("        function Validate() {\r\n");
      out.write("            var password = document.getElementById(\"txtPassword\").value;\r\n");
      out.write("            var confirmPassword = document.getElementById(\"txtConfirmPassword\").value;\r\n");
      out.write("            if (password != confirmPassword) {\r\n");
      out.write("                alert(\"Passwords do not match.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("    </script>  \r\n");
      out.write("    \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("/* Dropdown Button */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* The container <div> - needed to position the dropdown content */\r\n");
      out.write(".dropdown {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Dropdown Content (Hidden by Default) */\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  background-color: #f1f1f1;\r\n");
      out.write("  min-width: 160px;\r\n");
      out.write("  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Links inside the dropdown */\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("  color: black;\r\n");
      out.write("  padding: 12px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Change color of dropdown links on hover */\r\n");
      out.write(".dropdown-content a:hover {background-color: #ddd;}\r\n");
      out.write("\r\n");
      out.write("/* Show the dropdown menu on hover */\r\n");
      out.write(".dropdown:hover .dropdown-content {display: block;}\r\n");
      out.write("\r\n");
      out.write("/* Change the background color of the dropdown button when the dropdown content is shown */\r\n");
      out.write("/*.dropdown:hover .dropbtn {background-color: #11bba4d6;}\r\n");
      out.write("*/\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\" GenerateCaptcha()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- header -->\r\n");
      out.write("\t<header style=\"height: 116px; \tbackground-color: #0da8d6;\">\r\n");
      out.write("<img data-placeholder=\"no\" src=\"images/TutorCabin.jpg\" alt=\"TutorCabin\" style=\"padding: 35px 26px 43px 111px;\">\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("  <!-- nav start -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm bg-light navbar-light \">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <ul class=\"navbar-nav navbar-nav mr-auto\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
if(session.getAttribute("tutor")!=null) {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Dashboard.html\">Home&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Blogs.html\">Blogs&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Contact.html\">Contact&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Solved_Materials.html\">Solved Materials</a>\r\n");
      out.write("    </li>\r\n");
      out.write("   </ul> \r\n");
} else if(session.getAttribute("uemail")!=null) {
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Dashboard.html\">Home&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Find_Tutor.html\">Find Tutors&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("     <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Blogs.html\">Blogs&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Contact.html\">Contact&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Solved_Materials.html\">Solved Materials</a>\r\n");
      out.write("    </li>\r\n");
      out.write("   \r\n");
      out.write("  </ul>\r\n");
}
else{

      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Dashboard.html\">Home&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"About.html\" >About&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Join_As_A_Tutor.html\">Join As a Tutor&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Contact.html\">Contact&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Blogs.html\">Blogs&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    </ul>\r\n");
} 
      out.write('\r');
      out.write('\n');

if(session.getAttribute("uemail")!=null)
{

      out.write("\r\n");
      out.write("<span class=\"navbar-text\" style=\"padding-left: 150px; color: #a85486;\">\r\n");
      out.write("    \r\n");
      out.write("   <h5><a style=\"text-decoration: none;\" href=\"logout.html\"> |&nbsp  Logout &nbsp |</a></h5>\r\n");
      out.write("  </span>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</nav>\r\n");

}
else if(session.getAttribute("tutorEmail")!=null) {
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"dropdown\" style=\"margin-right: 10px;margin-top: -15px;\">\r\n");
      out.write("<img src=\"images/");
      out.print( session.getAttribute("tphoto") );
      out.write("\" alt=\"ram\" class=\"dropbtn\" style=\"border-radius:50px;margin-top:14px;\"width=\"30\" height=\"25\">\r\n");
      out.write("  <div class=\"dropdown-content\">\r\n");
      out.write("    <a href=\"teacherProfile.html\">View Profile</a>\r\n");
      out.write("    <a href=\"logout.html\">Logout</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<p style=\"margin-bottom: 5px;\"> ");
      out.print( session.getAttribute("tutorName") );
      out.write(" </p>\r\n");
      out.write("</nav>\r\n");
      out.write("\t\r\n");

}
else
{

      out.write("\r\n");
      out.write("<span class=\"navbar-text\" style=\"padding-left:150px; color: #a85486; float:right; \">\r\n");
      out.write("   <h5><a style=\"text-decoration: none;\" href=\"Login.html\"> |&nbsp  Login &nbsp |</a></h5>\r\n");
      out.write("  </span>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");

} 

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- nav End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- ADD NEW PRODUCT model is here -->\r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">Modal Header</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <p>Some text in the modal.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

	Datahelper.configureFile();
	Query q;
	
      out.write("\r\n");
      out.write("\t<div style =\"margin:\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<form action =\"changeName.html\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Old Name :</td>\r\n");
      out.write("\t<td><input type = \"text\" value = \"");
      out.print( session.getAttribute("tutorName"));
      out.write("\"></td>\r\n");
      out.write("\t\r\n");
      out.write("\t<td>New Name :</td>\r\n");
      out.write("\t<td><input type =\"text\" name =\"newName\"></td>\r\n");
      out.write("\t\r\n");
      out.write("\t<td>Enter password</td>\r\n");
      out.write("\t<td><input type =\"password\" name=\"password\"></td>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t<td></td>\r\n");
      out.write("\t<td>  <button type=\"button\" class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModal\">Open Modal</button>\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div style =\"margin:10% 40%\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<form action =\"changeEmail.html\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>Old Email :</td>\r\n");
      out.write("\t<td><input type = \"text\" value = \"");
      out.print( session.getAttribute("tutorEmail"));
      out.write("\"></td>\r\n");
      out.write("\r\n");
      out.write("\t<td>New Email :</td>\r\n");
      out.write("\t<td><input type =\"text\" name =\"newEmail\"></td>\r\n");
      out.write("\r\n");
      out.write("\t<td>Enter password</td>\r\n");
      out.write("\t<td><input type =\"password\" name=\"password\"></td>\r\n");
      out.write("\t\r\n");
      out.write("\t<td></td>\r\n");
      out.write("\t<td><input type =\"submit\" value =\"Change Email\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t</table></div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t<h2>Successfully Changed</h2>\r\n");
      out.write("\t<a href =\"dashboard.html\">Go To Home</a>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
