/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2020-04-02 10:17:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.uao;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("  \t<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-4.4.1-dist/css/bootstrap.min.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap-4.4.1-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-4.4.1-dist/css/Style.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>TutorCabin - Get Best Home Tutors in Indore</title>\r\n");
      out.write(" <script type=\"text/javascript\">  \r\n");
      out.write("        /* Function to Generat Captcha */  \r\n");
      out.write("        function GenerateCaptcha() {  \r\n");
      out.write("            var chr1 = Math.ceil(Math.random() * 10) + '';  \r\n");
      out.write("            var chr2 = Math.ceil(Math.random() * 10) + '';  \r\n");
      out.write("            var chr3 = Math.ceil(Math.random() * 10) + '';  \r\n");
      out.write("  \r\n");
      out.write("            var str = new Array(4).join().replace(/(.|$)/g, function () { return ((Math.random() * 36) | 0).toString(36)[Math.random() < .5 ? \"toString\" : \"toUpperCase\"](); });  \r\n");
      out.write("            var captchaCode = str + chr1 + ' ' + chr2 + ' ' + chr3;  \r\n");
      out.write("            document.getElementById(\"txtCaptcha\").innerHTML= captchaCode ;\r\n");
      out.write("        }  \r\n");
      out.write("        \r\n");
      out.write("        /* Function to Check Password and Re-password */\r\n");
      out.write("        function Validate() {\r\n");
      out.write("            var password = document.getElementById(\"txtPassword\").value;\r\n");
      out.write("            var confirmPassword = document.getElementById(\"txtConfirmPassword\").value;\r\n");
      out.write("            if (password != confirmPassword) {\r\n");
      out.write("                alert(\"Passwords do not match.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("    </script>  \r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\" GenerateCaptcha()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- header -->\r\n");
      out.write("\t<header style=\"height: 116px; \tbackground-color: #0da8d6;\">\r\n");
      out.write("<img data-placeholder=\"no\" src=\"images/TutorCabin.jpg\" alt=\"TutorCabin\" style=\"padding: 35px 26px 43px 111px;\">\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("  <!-- nav start -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm bg-light navbar-light \">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <ul class=\"navbar-nav navbar-nav mr-auto\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
if(session.getAttribute("tutor")!=null) {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Dashboard.html\">Home&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Blogs.html\">Blogs&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Contact.html\">Contact&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Solved_Materials.html\">Solved Materials</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    </ul>\r\n");
} else if(session.getAttribute("uemail")!=null) {
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Dashboard.html\">Home&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Find_Tutor.html\">Find Tutors&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("     <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Blogs.html\">Blogs&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Contact.html\">Contact&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Solved_Materials.html\">Solved Materials</a>\r\n");
      out.write("    </li>\r\n");
      out.write("   \r\n");
      out.write("  </ul>\r\n");
}
else{

      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Dashboard.html\">Home&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"About.html\" >About&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Join_As_A_Tutor.html\">Join As a Tutor&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Contact.html\">Contact&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"Blogs.html\">Blogs&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    </ul>\r\n");
} 
      out.write('\r');
      out.write('\n');

if(session.getAttribute("uemail")!=null)
{

      out.write("\r\n");
      out.write("<span class=\"navbar-text\" style=\"padding-left: 150px; color: #a85486;\">\r\n");
      out.write("    \r\n");
      out.write("   <h5><a style=\"text-decoration: none;\" href=\"logout.html\"> |&nbsp  Logout &nbsp |</a></h5>\r\n");
      out.write("  </span>\r\n");
      out.write("</nav>\r\n");

}
else if(session.getAttribute("tutor")!=null) {
	
      out.write("\r\n");
      out.write("\t<span class=\"navbar-text\" style=\"padding-left: 150px; color: #a85486;float:right;\">\r\n");
      out.write("    \r\n");
      out.write("   <h5><a style=\"text-decoration: none;\" href=\"logout.html\"> |&nbsp  Logout &nbsp |</a></h5>\r\n");
      out.write("  </span>\r\n");
      out.write("</nav>\r\n");
      out.write("\t\r\n");

}
else
{

      out.write("\r\n");
      out.write("<span class=\"navbar-text\" style=\"padding-left:150px; color: #a85486; float:right; \">\r\n");
      out.write("   <h5><a style=\"text-decoration: none;\" href=\"Login.html\"> |&nbsp  Login &nbsp |</a></h5>\r\n");
      out.write("  </span>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");

} 

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- nav End -->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
