/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2020-05-15 16:28:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.uao.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.hibernate.*;
import org.hibernate.cfg.*;
import java.util.*;
import template.*;
import dao.*;

public final class View_005fTutors_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("template");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.hibernate.cfg");
    _jspx_imports_packages.add("org.hibernate");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("  \t<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-4.4.1-dist/css/bootstrap.min.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap-4.4.1-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<title>TutorCabin - Get Best Home Tutors in Indore</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("  \r\n");
      out.write(".bg {\r\n");
      out.write("  /* The image used */\r\n");
      out.write("  background-image: url(\"images/Facultyimg.jpg\");\r\n");
      out.write("\r\n");
      out.write("  /* Full height */\r\n");
      out.write("  height: 100%;\r\n");
      out.write("\r\n");
      out.write("  /* Center and scale the image nicely */\r\n");
      out.write("  background-position: center;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("ul {\r\n");
      out.write("  list-style-type: none;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  width: 200px;\r\n");
      out.write("  border: 1px solid #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li a {\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  padding: 8px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  border-bottom: 1px solid #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li:last-child {\r\n");
      out.write("  border-bottom: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li a:hover:not(.active) {\r\n");
      out.write("  background-color: #555;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-sm-4{\r\n");
      out.write("\r\n");
      out.write("width: 200px; \r\n");
      out.write("height: 230px; \r\n");
      out.write("margin-top: 135px; \r\n");
      out.write("margin-left: 43px;\r\n");
      out.write("float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-sm-8{\r\n");
      out.write("\r\n");
      out.write("float: right;\r\n");
      out.write("    margin-top: 63px;\r\n");
      out.write("    margin-right: 95px;\r\n");
      out.write("    margin-bottom: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table{\r\n");
      out.write("align:center;\r\n");
      out.write("overflow:scroll\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table td{\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg\">\r\n");
      out.write("  <!-- header -->\r\n");
      out.write("  \r\n");
      out.write("<img  data-placeholder=\"no\" src=\"images/TutorCabin.jpg\" alt=\"TutorCabin\" style=\"padding: 35px 26px 43px 111px;opacity: 0.3;\">\r\n");
      out.write("<h3> <p align=\"center\" style=\"margin-top:-85px;\">|&nbsp Welcome to Admin Panel  &nbsp| </p> </h3>\r\n");
      out.write("  <hr>    \r\n");
      out.write("\r\n");
      out.write("<div class=\"col-sm-12\">\r\n");
      out.write("<div class=\"col-sm-4\">  \r\n");
      out.write("\r\n");
      out.write("<!-- nav start -->\r\n");
      out.write("  <ul class=\"navbar-nav \">\r\n");
      out.write("  \r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"admindash.html\">Home</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"viewreg.html\" >View Students</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"#\">View Discusion</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"#\">View Tutors</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      <a class=\"nav-link\" href=\"adminlogout.html\">Logout</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-sm-8 \">\r\n");
      out.write("\r\n");
      out.write("<h1>Registered Tutors</h1>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\"><tr><th>Photo</th><th>TUTOR NAME</th><th>EDUCATION</th><th>MOBILE NO.</th><th>EMAIL ID</th><th>SUBJECT</th><th>PASSWORD</th><th>ADDRESS</th><th>CITY</th><th>DOB</th><th>STATUS</th></tr>\r\n");

Datahelper.configureFile();
Query q=Datahelper.getRecord("from Tutor s");
List lst = q.list();
Iterator it = lst.iterator();
while(it.hasNext())
{
	Tutor tu = (Tutor)(it.next());
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<tr><td><img alt=\"");
      out.print( tu.getT_name() );
      out.write("\" src=\"images/");
      out.print( tu.getPhoto() );
      out.write("\" width=\"100\" height=\"100\"></td><td>");
      out.print( tu.getT_name() );
      out.write("</td><td>");
      out.print( tu.getEducation() );
      out.write("</td><td>");
      out.print( tu.getContact() );
      out.write("</td><td>");
      out.print( tu.getEmailid() );
      out.write("</td><td>");
      out.print( tu.getSubjecttoTeach() );
      out.write("</td><td>");
      out.print( tu.getPassword() );
      out.write("</td><td>");
      out.print( tu.getAddress() );
      out.write("</td><td>");
      out.print( tu.getCity() );
      out.write("</td><td>");
      out.print( tu.getDob() );
      out.write("</td><td><a href=\"managetutorstatus.html?q=");
      out.print( tu.getEmailid() );
      out.write('"');
      out.write('>');
      out.write(' ');
 if(tu.getStatus()==1){out.print("Blocked");}else {out.print("Approved");} 
      out.write("</a></td></tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
 }


Datahelper.closeConn();



      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("  <!-- nav End -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
